services:
  jaeger:
    container_name: jaeger
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.16.0
    ports:
      # TODO: Close for public access in production or secure with auth.
      - "16686:16686"
    expose:
      - "4317"
      - "4318"
    restart: unless-stopped
